version: '3'
services:
    apache:
        build:
            context: './images/apache2/'
        depends_on:
            - php
            - mysql
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www
            - ./images/apache2/key:/key
        container_name: apache
#    nginx:
#        image: nginx:latest
#        ports:
#            - "80:80"
##            - "443:443"
#        volumes:
#            - ./images/nginx/hosts:/etc/nginx/conf.d
#            - ./www:/var/www
#            - ./logs:/var/log/nginx
#        links:
#            - php
    php:
        build: ./images/php/7.4
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
#    mongo:
#        image: mongo
#        restart: always
#        environment:
#            MONGO_INITDB_ROOT_USERNAME:
#            MONGO_INITDB_ROOT_PASSWORD:
#        ports:
#            - "27017:27017"
#    mongo-express:
#        image: mongo-express
#        restart: always
#        ports:
#            - 8081:8081
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: root
#            ME_CONFIG_MONGODB_ADMINPASSWORD: example


